config/routes.rb
HighchartsBootstrap::Application.routes.draw do
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  root :to => 'visitors#new'
end

app/models/chart.rb
# encoding: utf-8
class Chart
  def self.basic_line_chart
    @chart = LazyHighCharts::HighChart.new('basic_line') do |f|
      f.chart({ type: 'line',
                marginRight: 130,
                marginBottom: 25 })
      f.title({  text: 'Monthly Average Temperature',
                 x: -20
      })
      f.xAxis({
         categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
      })
      f.yAxis({
        title: {
          text: 'Temperature (°C)'
        },
        plotLines: [{
          value: 0,
          width: 1,
          color: '#808080'
        }]
      })
      f.tooltip({
        valueSuffix: '°C'
      })
      f.legend({
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'top',
        x: -10,
        y: 100,
        borderWidth: 0
      })
      f.subtitle({
        text: 'Source: WorldClimate.com',
        x: -20
      })
      f.series({
        name: 'Tokyo',
        ldata: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
      })
      f.series(
        name: 'New York',
        data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
      )
      f.series({
        name: 'Berlin',
        data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
      })
      f.series({
          name: 'London',
          data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
      })
    end
  end

  #       Ajax loaded data, clickable points
  def self.line_ajax_chart

@csv = <<-EOJS
Day,Visits,Unique Visitors
3/9/13,5691,4346
3/10/13,5403,4112
3/11/13,15574,11356
3/12/13,16211,11876
3/13/13,16427,11966
3/14/13,16486,12086
3/15/13,14737,10916
3/16/13,5838,4507
3/17/13,5542,4202
3/18/13,15560,11523
3/19/13,18940,14431
3/20/13,16970,12599
3/21/13,17580,13094
3/22/13,17511,13234
3/23/13,6601,5213
3/24/13,6158,4806
3/25/13,17353,12639
3/26/13,17660,12768
3/27/13,16921,12389
3/28/13,15964,11686
3/29/13,12028,8891
3/30/13,5835,4513
3/31/13,4799,3661
4/1/13,13037,9503
4/2/13,16976,12666
4/3/13,17100,12635
4/4/13,15701,11394
4/5/13,14378,10530
4/6/13,5889,4521
4/7/13,6779,5109
4/8/13,16068,11599
EOJS

    @chart = LazyHighCharts::HighChart.new('line_ajax') do |f|
      f.title({
        text: 'Daily visits at www.highcharts.com'
      })
      f.subtitle({
        text: 'Source: Google Analytics'
      })
      f.xAxis({
        type: 'datetime',
        tickInterval: 7 * 24 * 3600 * 1000, # one_week
        tickWidth: 0,
          gridLineWidth: 1,
          labels: {
            align: 'left',
            x: 3,
            y: -3
          }
      })
      f.yAxis([{ #// left y axis
                title: {
                  text: nil
                },
                labels: {
                  align: 'left',
                  x: 3,
                  y: 16,
                  formatter: %|function() {
                    return Highcharts.numberFormat(this.value, 0);
                  }|.js_code
                },
                showFirstLabel: false
      },
      { #// right y axis
        linkedTo: 0,
        gridLineWidth: 0,
        opposite: true,
        title: {
          text: nil
        },
        labels: {
          align: 'right',
          x: -3,
          y: 16,
          formatter: %|function() {
            return Highcharts.numberFormat(this.value, 0);
          }|.js_code
        },
        showFirstLabel: false
      }
      ])
      f.legend({
        align: 'left',
        verticalAlign: 'top',
        y: 20,
        floating: true,
        borderWidth: 0
      })
      f.tooltip({
        shared: true,
        crosshairs: true
      })
      f.series({
        name: 'All visits',
        lineWidth: 4,
        marker: {
          radius: 4
        }
      })
      f.series({
        name: 'New visitors'
      })
    end

    @chart.options.merge!({data: {csv: @csv}})

    return @chart
  end


  def self.line_labels_chart
    @chart = LazyHighCharts::HighChart.new('line_labels') do |f|
      f.chart({
         type: 'line'
      })
      f.title({
        text: 'Monthly Average Temperature'
      })
      f.subtitle({
          text: 'Source: WorldClimate.com'
      })
      f.xAxis({
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
      })
      f.yAxis({
         title: {
                             text: 'Temperature (°C)'
                         }
      })
      f.tooltip({
        enabled: false,
        formatter: %|function() {
                             return '<b>'+ this.series.name +'</b><br/>'+
                                 this.x +': '+ this.y +'°C';
                         }|.js_code

      })
      f.plotOptions({
         line: {
                             dataLabels: {
                                                     enabled: true
                                                 },
                             enableMouseTracking: false
                         }
      })

      f.series({
         name: 'Tokyo',
         data: [7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
      })
      f.series({
          name: 'London',
          data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
      
      })

    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
# encoding: utf-8

class ChartsController < ApplicationController

  def basic_line
    @chart = Chart.basic_line_chart
  end

  def line_ajax
    @chart = Chart.line_ajax_chart
  end

  def line_labels
    @chart = Chart.line_labels_chart
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @chart = Chart.basic_line_chart
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/basic_line.js.erb
$('.js-basic_line').addClass('active').siblings().removeClass('active');

$('#basic_line')
  .append("<%= escape_javascript(
                          high_chart('chart_basic_line', @chart)) -%>")

app/views/charts/line_ajax.js.erb
$('.js-line_ajax').addClass('active').siblings().removeClass('active');

Highcharts.Data.prototype.dateFormats['m/d/Y'] = {
  regex: '^([0-9]{1,2})\\\\/([0-9]{1,2})\\\\/([0-9]{2})$',
  parser: function (match) {
    return Date.UTC(+('20' + match[3]), match[1] - 1, +match[2]);
  }
};

$('#line_ajax')
  .append("<%= escape_javascript(
                          high_chart('chart_line_ajax', @chart)) -%>")

app/views/charts/line_labels.js.erb
$('.js-line-labels').addClass('active').siblings().removeClass('active');


$('#line-labels')
  .append("<%= escape_javascript(
                          high_chart('chart_line-labels', @chart)) -%>")

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', page_path('about') %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".bs-docs-sidebar">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
Best Demo site for highcharts gem usage case.
</p>

app/views/visitors/new.html.erb
<% content_for :title, "Best Demo site for highcharts gem" %>
<h3>HighCharts gem Demo Site</h3>

<div class="container">
  <div class="row">
    <div class="span3 bs-docs-sidebar">
      <ul class="nav nav-list bs-docs-sidenav affix">
        <li class="js-basic_line">
        <%= link_to  basic_line_charts_path, remote: true do -%>
          <i class="icon-chevron-right"></i>Basic Liine
        <%- end -%>
        </li>
        <li class="js-line_ajax">
        <%= link_to  line_ajax_charts_path, remote: true do -%>
          <i class="icon-chevron-right"></i> Ajax loaded data, clickable points
        <%- end -%>
        </li>

        <li class="js-line-labels">
        <%= link_to  line_labels_charts_path, remote: true do -%>
          <i class="icon-chevron-right"></i> With data labels
        <%- end -%>
        </li>

      </ul>
    </div>

    <!-- demo charts master view -->
    <div class="span9">
      <section id="welcome_chart">
        <div class="page-header">
          <h1> Welcome to Highcharts Demo site! Lets's click left side's menu to render chart.</h1>
        </div>
      </section>
      <section id="basic_line">
        <div class="page-header">
          <h1> Basic Line</h1>
        </div>
      </section>

      <section id="line_ajax">
        <div class="page-header">
          <h1> Ajax loaded data, clickable points</h1>
        </div>
      </section>

      <section id="line-labels">
        <div class="page-header">
          <h1> With data labels</h1>
        </div>
      </section>
    </div>
  </div>
</div>